{{- $fullName := include "circle3_research_manager.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "circle3_research_manager.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ include "circle3_research_manager.domain" . | quote }}
      secretName: {{ include "circle3_research_manager.secretName" . | quote }}
  rules:
    - host: {{ include "circle3_research_manager.domain" .  | quote }}
      http:
        paths:
          - path: /research
            backend:
              serviceName: {{ $fullName }}
              servicePort: http