apiVersion: v1
appVersion: "1.0"
description: A single chart for installing whole sciebo rds ecosystem. Holds the developer version, which will be copied to "all".
name: dev
version: 0.3.1
home: https://www.research-data-services.org/
engine: gotpl
keywords:
  - research
  - data
  - services
  - zenodo
maintainers:
  - email: peter.heiss@uni-muenster.de
    name: Heiss
details: This Helm chart provides a system to handle the research data in your cloud to push them to other services.
sources:
  - https://www.research-data-services.org/
icon: https://www.research-data-services.org/img/sciebo.png

