circle1-port-zenodo: {}
circle1-port-owncloud: {}
circle2-exporter-service: {}
circle2-port-service: {}
circle2-metadata-service: {}
circle3-token-storage: {}
circle3-research-manager: {}
jaeger:
  ## All jaeger options: https://github.com/jaegertracing/helm-charts
  fullnameOverride: jaeger
  cassandra:
    config:
      max_heap_size: 1024M
      heap_new_size: 256M
    resources:
      requests:
        memory: 2048Mi
        cpu: 0.4
      limits:
        memory: 2048Mi
        cpu: 0.4
  schema:
    activeDeadlineSeconds: 600
redis-ha:
  ## All redis-ha options: https://github.com/DandyDeveloper/charts/tree/master/charts/redis-ha
  fullnameOverride: redis-ha
  redis:
    config:
      ## All redis options: http://download.redis.io/redis-stable/redis.conf
      min-replicas-to-write: 1
      min-replicas-max-lag: 5
      maxmemory: "0"
      maxmemory-policy: "volatile-lru"
      save: "60 1"
      repl-diskless-sync: "yes"
      rdbcompression: "yes"
      rdbchecksum: "yes"
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations: {}
  init:
    resources: {}
  emptyDir: {}
