global:
  domain: localhost
  ingress:
    tls:
      secretName: sciebords-tls-public
feature:
  jaeger: true
  redis: true
circle1-port-zenodo:
  enabled: false
circle1-port-owncloud:
  enabled: false
circle1-port-openscienceframework:
  enabled: false
circle1-port-datasafe:
  enabled: false
circle2-exporter-service: {}
circle2-port-service: {}
circle2-metadata-service: {}
circle3-token-storage: {}
circle3-research-manager: {}
jaeger:
  provisionDataStore:
    cassandra: true
    elasticsearch: false
    kafka: false
  ## All jaeger options: https://github.com/jaegertracing/helm-charts
  fullnameOverride: jaeger
  cassandra:
    config:
      max_heap_size: 1024M
      heap_new_size: 256M
    resources:
      requests:
        memory: 2048Mi
        cpu: 0.4
      limits:
        memory: 2048Mi
        cpu: 0.4
  schema:
    activeDeadlineSeconds: 600
redis:
  ## All redis-cluster options: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster
  fullnameOverride: redis
  usePassword: false
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations: {}
  redis:
    config:
      ## All redis options: http://download.redis.io/redis-stable/redis.conf
      min-replicas-to-write: 1
      min-replicas-max-lag: 5
      maxmemory: "0"
      maxmemory-policy: "volatile-lru"
      save: "60 1"
      repl-diskless-sync: "yes"
      rdbcompression: "yes"
      rdbchecksum: "yes"
