global:
  domain: localhost
  ingress:
    tls:
      secretName: sciebords-tls-public
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_HELPER_HOST: redis-helper
  REDIS_HELPER_PORT: 6379
feature:
  jaeger: true
  redis: true
layer0-web:
  enabled: false
layer0-describo:
  enabled: false
circle1-port-zenodo:
  enabled: false
circle1-port-owncloud:
  enabled: false
circle1-port-openscienceframework:
  enabled: false
circle1-port-datasafe:
  enabled: false
circle1-port-reva:
  enabled: false
circle2-exporter-service: {}
circle2-port-service: {}
circle2-metadata-service: {}
circle3-token-storage: {}
circle3-research-manager: {}
jaeger:
  ## All jaeger options: https://github.com/jaegertracing/helm-charts
  fullnameOverride: jaeger
  schema:
    activeDeadlineSeconds: 600
redis:
  ## All redis-cluster options: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster
  fullnameOverride: redis
  usePassword: false
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations: {}
  redis:
    config:
      ## All redis options: http://download.redis.io/redis-stable/redis.conf
      min-replicas-to-write: 1
      min-replicas-max-lag: 5
      maxmemory: "0"
      maxmemory-policy: "volatile-lru"
      save: "60 1"
      repl-diskless-sync: "yes"
      rdbcompression: "yes"
      rdbchecksum: "yes"
redis-helper:
  ## All redis-cluster options: https://github.com/bitnami/charts/tree/master/bitnami/redis
  fullnameOverride: redis-helper
  usePassword: false
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations: {}
  redis:
    config:
      ## All redis options: http://download.redis.io/redis-stable/redis.conf
      min-replicas-to-write: 1
      min-replicas-max-lag: 5
      maxmemory: "0"
      maxmemory-policy: "volatile-lru"
      save: "60 1"
      repl-diskless-sync: "yes"
      rdbcompression: "yes"
      rdbchecksum: "yes"
